forms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('test/', views.TestView.as_view(), name='test_form'),
    path('test/send/', views.TestFormCreate.as_view(), name='test_form_send'),
    path('callback/send/', views.CallbackFormCreate.as_view(), name='callback_form_send'),
    path('contact/send/', views.ContactFormCreate.as_view(), name='contact_form_send'),
    path('service/send/', views.ServiceFormCreate.as_view(), name='service_form_send'),
    path('equipment/send/', views.EquipmentFormCreate.as_view(), name='equipment_form_send'),
]

services/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ServicesView.as_view(), name='services'),
    path('<str:slug>/', views.ServicesDetailView.as_view(), name='service_detail'),
]

stabur/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from services import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('uslugi/', include('services.urls')),
    path('o-kompanii/', views.AboutView.as_view(), name='about'),
    path('proekty/', views.ProjectsView.as_view(), name='projects'),
    path('tehnika/', views.EquipmentView.as_view(), name='equipment'),
    path('kontakty/', views.ContactsView.as_view(), name='contacts'),
    path('politika-konfidencialnosti/', views.PrivacyView.as_view(), name='privacy'),
    path('tinymce/', include('tinymce.urls')),
    path('forms/', include('forms.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/models.py
from django.db import models
from tinymce.models import HTMLField
from django.urls import reverse


class Service(models.Model):
    ''' Модель услуги '''

    slug = models.SlugField('Слаг')
    title = models.CharField('Название', max_length=200)
    title_full = models.CharField(
        'Название полное', max_length=250, blank=True)
    description = HTMLField('Описание')
    description_full = HTMLField('Описание полное', blank=True)
    image_preview = models.ImageField('Превью')
    image_detail = models.ImageField('Детальная картинка')
    types_header = models.CharField(
        'Заголовок для дополнительных услуг', max_length=200, blank=True)
    types_text = HTMLField('Текст для дополнительных услуг', blank=True)
    projects_header = models.CharField(
        'Заголовок для проектов', max_length=200, blank=True)
    projects_text = HTMLField('Текст для проектов', blank=True)
    projects = models.ManyToManyField(
        'Project', related_name='projects', blank=True, verbose_name='Проекты')
    equipment_header = models.CharField(
        'Заголовок для техники', max_length=200, blank=True)
    equipment_text = HTMLField('Текст для техники', blank=True)
    equipment = models.ManyToManyField(
        'Equipment',
        related_name='equipment',
        blank=True,
        verbose_name='Техника')

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'

    def get_absolute_url(self):
        return reverse('service_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title


class Scheme(models.Model):
    ''' Модель схемы '''

    scheme = models.OneToOneField(
        'Service', null=True, on_delete=models.CASCADE, verbose_name='Схема', related_name="scheme")
    header = models.CharField('Заголовок', max_length=200)
    text_top = HTMLField('Текст вверху')
    text_bottom = HTMLField('Текст внизу')

    class Meta:
        verbose_name = 'Схема работы'
        verbose_name_plural = 'Схемы работы'

    def __str__(self):
        return self.scheme.title


class SchemeItem(models.Model):
    ''' Модель пункта схемы '''

    scheme = models.ForeignKey('Scheme', null=True, on_delete=models.CASCADE,
                               verbose_name='Пункт схемы', related_name="items")
    title = models.CharField('Заголовок', max_length=100)
    value = HTMLField('Текст')

    class Meta:
        verbose_name = 'Пункт схемы'
        verbose_name_plural = 'Пункты схемы'

    def __str__(self):
        return self.title


class Type(models.Model):
    ''' Модель дополнительной услуги '''

    service = models.ForeignKey('Service', null=True, on_delete=models.CASCADE,
                                verbose_name='Дополнительная услуга', related_name="types")
    title = models.CharField('Название', max_length=200)
    description = HTMLField('Описание')
    image = models.ImageField('Картинка')

    class Meta:
        verbose_name = 'Дополнительная услуга'
        verbose_name_plural = 'Дополнительные услуги'

    def __str__(self):
        return self.title


class Project(models.Model):
    ''' Модель проекта '''

    title = models.CharField('Название', max_length=200)
    description = HTMLField('Описание')

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def __str__(self):
        return self.title


class ProjectImage(models.Model):
    ''' Модель картинки проекта '''

    project = models.ForeignKey(
        'Project', null=True, on_delete=models.CASCADE, related_name='images', verbose_name='Проект')
    image = models.ImageField('Картинка')

    class Meta:
        verbose_name = 'Картинка проекта'
        verbose_name_plural = 'Картинки проекта'

    def __str__(self):
        return ''


class ProjectProperty(models.Model):
    ''' Модель свойства проекта '''

    project = models.ForeignKey('Project', null=True, on_delete=models.CASCADE,
                                verbose_name='Проект', related_name="properties")
    title = models.ForeignKey('ProjectPropertyName', null=True,
                              on_delete=models.SET_NULL, verbose_name='Свойство')
    value = models.CharField('Значение', max_length=100)

    class Meta:
        verbose_name = 'Свойство проекта'
        verbose_name_plural = 'Свойства проекта'

    def __str__(self):
        return ''


class ProjectPropertyName(models.Model):
    ''' Модель названия свойства проекта '''

    title = models.CharField('Название', max_length=200)

    class Meta:
        verbose_name = 'Свойство проекта'
        verbose_name_plural = 'Свойства проекта'

    def __str__(self):
        return self.title


class Equipment(models.Model):
    ''' Модель техники '''

    title = models.CharField('Название', max_length=200)
    price = models.PositiveIntegerField('Цена')
    price_type = models.ForeignKey(
        'EquipmentPrice', null=True, on_delete=models.SET_NULL, verbose_name='Тип цены')
    image = models.ImageField('Картинка')

    class Meta:
        verbose_name = 'Техника'
        verbose_name_plural = 'Техника'

    def __str__(self):
        return self.title


class EquipmentPrice(models.Model):
    ''' Модель типа цен техники '''

    title = models.CharField('Название', max_length=10)

    class Meta:
        verbose_name = 'Тип цены'
        verbose_name_plural = 'Типы цены'

    def __str__(self):
        return self.title


class EquipmentProperty(models.Model):
    ''' Модель свойства техники '''

    equipment = models.ForeignKey('Equipment', null=True, on_delete=models.CASCADE,
                                  verbose_name='Техника', related_name="properties")
    title = models.ForeignKey('EquipmentPropertyName', null=True,
                              on_delete=models.SET_NULL, verbose_name='Свойство')
    value = models.CharField('Значение', max_length=100)

    class Meta:
        verbose_name = 'Свойство'
        verbose_name_plural = 'Свойства'

    def __str__(self):
        return ''


class EquipmentPropertyName(models.Model):
    ''' Модель названия свойства техники '''

    title = models.CharField('Название', max_length=200)

    class Meta:
        verbose_name = 'Свойство техники'
        verbose_name_plural = 'Свойства техники'

    def __str__(self):
        return self.title


class Document(models.Model):
    ''' Модель документа '''

    title = models.CharField('Название', max_length=100)
    image = models.ImageField('Картинка')

    class Meta:
        verbose_name = 'Документ'
        verbose_name_plural = 'Документы'

    def __str__(self):
        return self.title


class Contact(models.Model):
    ''' Контакты '''

    ceo = models.CharField('Директор', max_length=100)
    full_name = models.CharField(
        'Полное наименование организации', max_length=250)
    left = HTMLField('Левая колонка')
    right = HTMLField('Правая колонка')
    email = models.CharField('E-mail', max_length=100)
    phone = models.CharField('Номер тел./факс', max_length=20)
    address = models.CharField('Юридический и почтовый адрес', max_length=200)
    telegram = models.CharField(max_length=200, blank=True, null=True)
    whatsapp = models.CharField(max_length=200, blank=True, null=True)


    class Meta:
        verbose_name = 'Контакты'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        return self.full_name

forms/tests.py
from django.test import TestCase

# Create your tests here.

services/views.py
from django.shortcuts import render
from django.views.generic.base import View
from django.views.generic import ListView, DetailView
from forms import forms
from . import models


# class HomeView(View):
#     def get(self, request):
#         projects = models.Project.objects.all()[:6]
#         equipment = models.Equipment.objects.all()
#         services = models.Service.objects.all()
#         documents = models.Document.objects.all()
#         return render(request, 'services/home.html', {
#             'projects': projects,
#             'equipment': equipment,
#             'services': services,
#             'documents': documents,
#             'title': 'Главная страница'
#         })


class HomeView(ListView):
    model = models.Service
    template_name = 'services/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = models.Project.objects.all()[:6]
        context['equipment'] = models.Equipment.objects.all()
        context['services'] = models.Service.objects.all()
        context['documents'] = models.Document.objects.all()
        context['title'] = 'Главная страница'
        return context


class ServicesView(ListView):
    model = models.Service

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Услуги'
        return context


class ServicesDetailView(DetailView):
    model = models.Service


class AboutView(ListView):
    model = models.Document
    template_name = 'services/about.html'
    context_object_name = 'documents'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'О компании'
        return context


class ProjectsView(ListView):
    model = models.Project
    template_name = 'services/projects.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Проекты'
        return context


class EquipmentView(ListView):
    model = models.Equipment
    template_name = 'services/equipment.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Техника'
        return context


class ContactsView(View):
    def get(self, request):
        form = forms.ContactForm()
        contacts = models.Contact.objects.first()
        return render(request, 'services/contacts.html', {
            'form': form,
            'contacts': contacts,
            'title': 'Контакты'
        })


class PrivacyView(View):
    def get(self, request):
        contacts = models.Contact.objects.first()
        return render(request, 'services/privacy.html', {
            'title': 'Политика конфиденциальности',
            'contacts': contacts,
        })

services/templates/services/about.html
{% extends 'services/base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

<div class="about" id="about">
	<div class="container">
		<h2 class="about__header">О компании</h2>
		<div class="about__text">Компания ООО «СпецТехноАльянс» выполняет все работы нулевого цикла строительства под ключ, включая инженерные изыскания. Для этого у нас имеются все необходимые допуски, высококвалифицированные специалисты и оборудование.</div>
		<div class="about__inner flex">
			<div class="about__left"><img class="about__image" src="{% static 'img/about-image.png' %}" alt=""></div>
			<div class="about__right">
				<div class="about__text_2"><strong>Компания работает на строительном рынке с 2015 года.</strong> За это время накоплен значительный опыт в строительной отрасли.</div>
				<div class="about__right-text">Использование современных технологий и опыт наших специалистов позволяют сократить сроки выполнения земляных работ и устройства фундаментов до 40% по сравнению с аналогичными предложениями на рынке, и выполнять работы качественно, в сжатые сроки на взаимовыгодных условиях. <br><br>Правила и порядок проведения инженерных изысканий регламентируется государственными стандартами действующими на территории РФ.</div>
			</div>
		</div>
	</div>
</div>
{% include 'services/include/docs.html' %}
<div class="benefits" id="benefits">
	<div class="container">
		<div class="benefits-items flex">
			<div class="benefits__item">
				<h2 class="benefits__header">Еще несколько причин начать работать с нами</h2>
			</div>
			<div class="benefits__item">Работаем в неблагоприятных природно-техногенных условиях. Выполняем работы в условиях неустойчивого и водонасыщенного грунта, подтопляемых участках. Разрабатываем мероприятия инженерной защиты территории предполагаемого строительства.</div>
			<div class="benefits__item">Наши специалисты-проектировщики индивидуально под ваш объект предложат технические решения, которые обеспечат снижение затрат без ущерба качества работ с сохранением несущей способности оснований.</div>
			<div class="benefits__item">Наши специалисты-проектировщики индивидуально под ваш объект предложат технические решения, которые обеспечат снижение затрат без ущерба качества работ с сохранением несущей способности оснований.</div>
			<div class="benefits__item">Наши специалисты-проектировщики индивидуально под ваш объект предложат технические решения, которые обеспечат снижение затрат без ущерба качества работ с сохранением несущей способности оснований.</div>
			<div class="benefits__item">Наши специалисты-проектировщики индивидуально под ваш объект предложат технические решения, которые обеспечат снижение затрат без ущерба качества работ с сохранением несущей способности оснований.</div>
		</div>
	</div>
</div>

{% endblock content %}

services/templates/services/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
	<meta charset="utf-8">
	<title>{% block title %}{% endblock title %}</title>
	<meta name="description" content="Главная страница">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" href="{% static 'img/favicon.ico' %}">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@600&amp;display=swap">
	<link rel="stylesheet" href="{% static 'css/libs.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body {% if request.path != "/" %} class="inner" {% endif %}>
	{% include 'services/include/header.html' %}
	<main class="content">
		{% block content %}
		{% endblock content %}
	</main>
	{% include 'services/include/footer.html' %}
	{% include 'services/include/modals.html' %}
	<div class="fas fa-arrow-up" id="top"></div>
	<script src="{% static 'js/libs.min.js' %}"></script>
	<script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

services/templates/services/contacts.html
{% extends 'services/base.html' %}
{% load static %}
{% load tags %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

<div class="requisites" id="requisites">
	<div class="container">
		<h2 class="requisites__header">Контакты и реквизиты</h2>
		<div class="requisites__inner">
			<div class="requisites__top">
				<p><strong>Директор:</strong> {{ contacts.ceo }}</p>
				<p><strong>Полное наименование организации:</strong> {{ contacts.full_name }}</p>
			</div>
			<div class="requisites__left">{{ contacts.left|safe }}</div>
			<div class="requisites__right">{{ contacts.right|safe }}</div>
			<div class="requisites__bottom">
				<p><strong>E-mail:</strong> <a href="mailto:{{ contacts.email }}">{{ contacts.email }}</a></p>
				<p><strong>Номер тел./факс:</strong> {% get_phone %}</p>
				<p><strong>Юридический и&nbsp;почтовый адрес:</strong> {{ contacts.address }}</p>
			</div>
		</div>
	</div>
</div>
<div class="order" id="order">
	<div class="container">
		<div class="order__inner flex">
			<div class="order__left">
				<h2 class="order__header">Задать вопрос</h2>
				<form method="post" action="{% url 'contact_form_send' %}" class="order-form flex jcsb">
					{% csrf_token %}
					<label class="order-form__label order-form__label-name">
						<div class="order-form__label-text">Ваше имя</div>
						{{ form.name }}
					</label>
					<label class="order-form__label order-form__label-phone">
						<div class="order-form__label-text">Ваш номер телефона</div>
						{{ form.phone }}
					</label>
					<label class="order-form__label order-form__label-comment">
						<div class="order-form__label-text">Ваше сообщение</div>
						{{ form.comment }}
					</label>
					<button class="order-form__button btn btn_yellow" type="submit"><span>Отправить
							сообщение</span></button>
					<label class="order-form__label order-form__label-privacy">
						<input type="checkbox" required>Принимаю условия обработки моих данных в соответствии с <a
							href="{% url 'privacy' %}">политикой обработки данных</a>
					</label>
				</form>
			</div>
			<div class="order__right order__right_contacts">
				<div class="map">
					<script type="text/javascript" charset="utf-8" async
						src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A4b24180aaf51dcc62906c93e66945258566003a0ca2e234b7fb31f7d871f4320&amp;width=100%&amp;height=100%&amp;lang=ru_RU&amp;scroll=false"></script>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

services/templates/services/equipment.html
{% extends 'services/base.html' %}
{% load tags %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

<div class="equipment" id="equipment">
	<div class="container">
		<h2 class="equipment__header">Буровая техника</h2>
		<div class="equipment__subheader subheader">Буровые установки в аренду в Калуге</div>
		<div class="equipment__text">
			<p>В нашей компании имеется вся необходимая техника для выполнения работ нулевого цикла строительства и инженерных изысканий. Мы предоставляем в пользование строительную технику, как юридическим, так и частным лицам. Вся техника предоставляется в аренду только со своим оператором или бригадой.</p>
			<p>Итоговая стоимость аренды будет зависеть от сложности, объема работ и удаленности объекта производства работ.</p>
			<p>Уточняйте стоимость аренды по телефону {% get_phone %}</p>
		</div>
		<div class="equipment-items">
			{% for item in equipment_list %}
			<div class="equipment__item">
				<div class="equipment__item-inner shadow flex">
					<div class="equipment__item-image-part">
						<img class="equipment__item-image" src="{{ item.image.url }}" alt="">
					</div>
					<div class="equipment__item-text-part">
						<div class="equipment__item-name">{{ item.title|safe }}</div>
						<ul>
							{% for property in item.properties.all %}
							<li><strong>{{ property.title|safe }}</strong>: {{ property.value|safe }}</li>
							{% endfor %}
						</ul>
						<div class="equipment__item-bottom flex">
							<div class="equipment__item-prices">
								<div class="equipment__item-prices-text">от</div>
								<div class="equipment__item-price"><span>{{ item.price|safe }}</span> ₽/{{ item.price_type|safe }}</div>
							</div>
							<a class="equipment__item-button btn btn_yellow" href="#order_equipment" data-name="{{ item.title }}"><span>Заказать</span></a>
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</div>

{% endblock content %}

services/templates/services/home.html
{% extends 'services/base.html' %}
{% load static %}
{% load forms %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

<div class="services" id="services">
	<div class="container">
		<h2 class="services__header">Наши услуги</h2>
		<div class="services-buttons">
			<div class="swiper-button-prev services-button-prev"></div>
			<div class="swiper-button-next services-button-next"></div>
		</div>
	</div>
	<div class="swiper-container">
		<div class="services-items swiper-wrapper">
			{% for service in services %}
			<div class="services__item swiper-slide">
				<div class="services__item-image-part">
					<img class="services__item-image" src="{{ service.image_preview.url }}" alt="">
					<div class="services__item-hidden">
						<div class="services__item-text">{{ service.description|safe }}</div>
						<a class="services__item-button btn btn_white" href="{{ service.get_absolute_url }}"><span>Подробнее</span></a>
					</div>
				</div><a class="services__item-text-part" href="{{ service.get_absolute_url }}">{{ service.title|safe }}</a>
			</div>
			{% endfor %}
		</div>
	</div>
	<div class="container">
		<div class="swiper-scrollbar services-scrollbar"></div>
	</div>
</div>
<div class="equipment" id="equipment">
	<div class="container">
		<h2 class="equipment__header">Наша техника</h2>
		<div class="equipment__text">Наша компания является собственником буровой техники. Мы гарантируем ее исправность и отсутствие проблем в процессе эксплуатации. Вся техника соответствует техническим регламентам и имеет регистрацию в контролирующих органах</div>
	</div>
	<div class="swiper-container">
		<div class="equipment-items swiper-wrapper">
			{% for item in equipment %}
			<div class="equipment__item swiper-slide">
				<div class="equipment__item-inner shadow flex">
					<div class="equipment__item-image-part">
						<img class="equipment__item-image" src="{{ item.image.url }}" alt="">
					</div>
					<div class="equipment__item-text-part">
						<div class="equipment__item-name">{{ item.title|safe }}</div>
						<ul>
							{% for property in item.properties.all %}
							<li><strong>{{ property.title|safe }}</strong>: {{ property.value|safe }}</li>
							{% endfor %}
						</ul>
						<div class="equipment__item-bottom flex">
							<div class="equipment__item-prices">
								<div class="equipment__item-prices-text">от</div>
								<div class="equipment__item-price"><span>{{ item.price|safe }}</span> ₽/{{ item.price_type|safe }}</div>
							</div>
							<a class="equipment__item-button btn btn_yellow" href="#order_equipment" data-name="{{ item.title }}"><span>Заказать</span></a>
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		<div class="equipment-buttons">
			<div class="swiper-button-prev equipment-button-prev"></div>
			<div class="swiper-button-next equipment-button-next"></div>
		</div>
	</div>
	<div class="swiper-pagination equipment-pagination"></div>
</div>
<div class="about" id="about">
	<div class="container">
		<h2 class="about__header">Компания СпецТехноАльянс</h2>
		<div class="about__text">Наша компания располагает современной буровой техникой, имеет штат профессиональных специалистов с большим стажем и опытом работы. Машины и оборудование соответствует требованиям Технических регламентов и зарегистрированы в контролирующих органах.</div>
		<div class="about__inner flex">
			<div class="about__left"><img class="about__image" src="{% static 'img/about-image.png' %}" alt=""></div>
			<div class="about__right">
				<div class="about__text_2"><strong>Компания работает на строительном рынке с 2015 года.</strong> За это время накоплен значительный опыт в строительной отрасли.</div>
				<div class="about-items flex">
					<div class="about__item flex">
						<div class="about__item-image-part">
							<img class="about__item-image" src="{% static 'img/svg/about-06.svg' %}" alt="">
							<!-- <svg class="about__item-image">
								<use xlink:href="{% static 'img/svg/about-06.svg' %}"></use>
							</svg> -->
						</div>
						<div class="about__item-text-part">Доступные цены</div>
					</div>
					<div class="about__item flex">
						<div class="about__item-image-part">
							<img class="about__item-image" src="{% static 'img/svg/about-02.svg' %}" alt="">
							<!-- <svg class="about__item-image">
								<use xlink:href="{% static 'img/sprite.svg#about-02' %}"></use>
							</svg> -->
						</div>
						<div class="about__item-text-part">Более 300 объектов</div>
					</div>
					<div class="about__item flex">
						<div class="about__item-image-part">
							<img class="about__item-image" src="{% static 'img/svg/about-03.svg' %}" alt="">
							<!-- <svg class="about__item-image">
								<use xlink:href="{% static 'img/sprite.svg#about-03' %}"></use>
							</svg> -->
						</div>
						<div class="about__item-text-part">Гарантированный результат</div>
					</div>
					<div class="about__item flex">
						<div class="about__item-image-part">
							<img class="about__item-image" src="{% static 'img/svg/about-04.svg' %}" alt="">
							<!-- <svg class="about__item-image">
								<use xlink:href="{% static 'img/sprite.svg#about-04' %}"></use>
							</svg> -->
						</div>
						<div class="about__item-text-part">Сжатые сроки</div>
					</div>
					<div class="about__item flex">
						<div class="about__item-image-part">
							<img class="about__item-image" src="{% static 'img/svg/about-05.svg' %}" alt="">
							<!-- <svg class="about__item-image">
								<use xlink:href="{% static 'img/sprite.svg#about-05' %}"></use>
							</svg> -->
						</div>
						<div class="about__item-text-part">Высокая квалификация</div>
					</div>
					<div class="about__item flex">
						<div class="about__item-image-part">
							<img class="about__item-image" src="{% static 'img/svg/about-01.svg' %}" alt="">
							<!-- <svg class="about__item-image">
								<use xlink:href="{% static 'img/sprite.svg#about-01' %}"></use>
							</svg> -->
						</div>
						<div class="about__item-text-part">Многолетний опыт</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% include 'services/include/docs.html' %}

<div class="portfolio" id="portfolio">
	<div class="container">
		<h2 class="portfolio__header">Выполненные проекты <br>компании СпецТехноАльянс</h2>
		<div class="portfolio-items flex">
			{% for project in projects %}
			<div class="portfolio__item">
				<div class="portfolio__item-image-part">
					{% with project.images.all|first as image %}
					<img class="portfolio__item-image" src="{{ image.image.url }}" alt="">
					{% endwith %}
					<div class="portfolio__item-hidden">
						<div class="portfolio__item-hidden-inner">
							<h3 class="portfolio__item-hidden-header">{{ project.description|safe }}</h3>
							<ul>
								{% for property in project.properties.all %}
								<li><strong>{{ property.title|safe }}:</strong> {{ property.value|safe }}</li>
								{% endfor %}
							</ul>
						</div><a class="portfolio__item-button btn btn_white" href="{% url 'projects' %}#project-{{ project.id }}"><span>Подробнее</span></a>
					</div>
				</div><a class="portfolio__item-text-part" href="{% url 'projects' %}#project-{{ project.id }}">{{ project.title|safe }}</a>
			</div>
			{% endfor %}
			<a class="portfolio__button btn btn_grey" href="{% url 'projects' %}"><span>Смотреть ещё проекты →</span></a>
		</div>
	</div>
</div>

{% get_order %}

{% endblock content %}

services/templates/services/projects.html
{% extends 'services/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

<div class="portfolio" id="portfolio">
	<div class="container">
		<h2 class="portfolio__header">Буровые и земляные работы СпецТехноАльянс</h2>
		<div class="portfolio-items">
			{% for project in project_list %}
			<div class="portfolio__item" id="project-{{ project.id }}">
				<div class="portfolio__item-inner shadow">
					<div class="portfolio__item-image-part swiper-container">
						<div class="swiper-wrapper">
							{% for image in project.images.all %}
							<a class="portfolio__item-link swiper-slide" href="{{ image.image.url }}">
								<img class="portfolio__item-image" src="{{ image.image.url }}" alt="">
							</a>
							{% endfor %}
						</div>
						<div class="portfolio-buttons">
							<div class="swiper-button-prev portfolio-button-prev"></div>
							<div class="swiper-button-next portfolio-button-next"></div>
						</div>
						<div class="swiper-pagination portfolio-pagination"></div>
					</div>
					<div class="portfolio__item-text-part">
						<div class="portfolio__item-header">{{ project.title|safe }}</div>
						<div class="portfolio__item-text">{{ project.description|safe }}</div>
						<ul>
							{% for property in project.properties.all %}
							<li><strong>{{ property.title|safe }}</strong>: {{ property.value|safe }}</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</div>

{% endblock content %}

services/templates/services/service_list.html
{% extends 'services/base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

<div class="services" id="services">
	<div class="container">
		<h2 class="services__header">Наши услуги</h2>
		<div class="services-items">
			{% for service in service_list %}
			<div class="services__item">
				<div class="services__item-inner shadow">
					<div class="services__item-text-part">
						<p class="services__item-header">{{ service.title|safe }}</p>
						{{ service.description_full|safe }}
						<!-- <a class="services__item-button btn btn_yellow" href="{% url 'service_detail' service.slug %}"><span>Подробнее</span></a> -->
						<a class="services__item-button btn btn_yellow" href="{{ service.get_absolute_url }}"><span>Подробнее</span></a>
					</div>
					<div class="services__item-image-part">
						<img class="services__item-image" src="{{ service.image_preview.url }}" alt="{{ service.title }}">
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</div>

{% endblock content %}